### ISSUE TITLE
Haskell guide suggestions

### ISSUE THREAD

**Issue by Warbo** [theindigamer/not-a-blog#1]
Hello, I enjoyed your "Opinionated Haskell Guide 2019" and wanted to make a couple of suggestions. I don't have a reddit account, so thought I'd post them here (if you're gonna use github as a blog, I'm gonna use issues as comments ;) )

## Hoogle ##

Since you suggest installing Hoogle as a search provider, I thought I'd mention that DuckDuckGo will redirect to hoogle.haskell.org if the query includes `!hoogle`. Many people (including me) have DuckDuckGo as their default search engine, so it's handy that it has [a few Haskell-specific features](https://duckduckgo.com/bang?c=Tech&sc=Languages+(Haskell))

## Partial Functions ##

I agree about trying to avoid them. You suggest using comments to explain why (we think) errors won't happen. I would also suggest that partial functions should always prefer calling `error` rather than using `undefined` or leaving cases unhandled. This way we can at least write an informative message (possibly containing argument values, etc.). Much better to see a custom message like `Couldn't foo 7 because it is odd` rather than the less-helpful `Exception: Prelude.undefined` or `Non-exhaustive patterns in function foo`.

**Comment by typesanitizer** [comment]
Thanks for the suggestions! I've incorporated these into the latest version.
